name: freepose
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pip
  - wget
  - pip:
    - torch==2.4.0
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - torchvision
    - opencv-python
    - matplotlib
    - numpy
    - tqdm
    - scipy
    - scikit-image
    - scikit-learn
    - pandas
    - joblib
    - trimesh
    - pypng
    - imageio
    - progressbar
    - webdataset
    - open_clip_torch
    - loguru
    - einops
    - pyrender
    - ninja
    - transformers==4.46.1
    - xformers
    - timm==0.6.7
    - open3d
    - pin
    - objaverse
